development:
  sessions:
    default:
      database: bookstash_development
      hosts:
        - localhost:27049
      options:
        consistency: :eventual
        safe: true
  options:
    use_utc: true

test:
  sessions:
    default:
      database: bookstash_test
      hosts:
        - localhost:27049
      options:
        consistency: :eventual
        safe: true
  options:
    use_utc: true
